[package]
name = "city2bal"
version = "0.1.0"
authors = ["Tristan Konolige <tristan.konolige@gmail.com>"]
build = "build.rs"

[dependencies]
tobj = "*"
cgmath = "*"
structopt = "*"
rand = "0.6"
ply-rs = "*"
poisson = {git = "https://github.com/WaDelma/poisson.git"}
nalgebra = "0.17"
itertools = "*"
embree-rs = {git = "https://github.com/tkonolige/embree-rs.git"}
# embree-rs = {path = "/Users/tristan/Sync/Research/bundle_adjustment/embree-rs"}
petgraph = "*"
rayon = "*"
nom = "*"
indicatif = {git = "https://github.com/mitsuhiko/indicatif.git", features=["with_rayon"]}
