name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: tkonolige/embree:3.8.0
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
    - uses: actions-rs/cargo@v1
      with:
        command: build
    - uses: actions-rs/cargo@v1
      with:
        command: test
