name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        curl -O -J -L https://github.com/embree/embree/releases/download/v3.8.0/embree-3.8.0.x86_64.linux.tar.gz
        tar xvf embree-3.8.0.x86_64.linux.tar.gz
        sudo cp embree-3.8.0.x86_64.linux/lib/* /usr/lib/
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
